# db_init.py
import sqlite3
from datetime import datetime

SECTION_A = [
    (1, "Why is it impossible to earn salvation through personal effort?",
     "Because salvation is too spiritual to work for",
     "Because grace excludes the need for any human responsibility",
     "Because no human work can satisfy God’s perfect justice",
     "Because the law only applies to the Old Testament"),
    (2, "What makes the idea of “righteousness” in Christ different from Old Testament righteousness?",
     "It is based entirely on grace and not performance",
     "It includes ceremonial purity and moral law",
     "It is received after proving one’s repentance",
     "It replaces the need for forgiveness"),
    (3, "What best reflects the nature of God’s justice in salvation?",
     "It is flexible because of His mercy",
     "It must punish sin even if the sinner is unaware",
     "It allows forgiveness without consequence",
     "It balances human effort with divine help"),
    (4, "What does it mean that Adam was a “corporate man”?",
     "He represented all humanity in spiritual leadership",
     "All humans were created as individuals after Adam",
     "His fall affected only his direct descendants",
     "All humanity was spiritually and legally included in him at creation"),
    (5, "Which best describes the role of faith in receiving grace?",
     "Faith convinces God to show mercy",
     "Faith makes you qualified for salvation",
     "Faith is your response to access the grace already made available",
     "Faith is a substitute for works in the New Testament"),
    (6, "What is the key difference between forgiveness and remission of sin?",
     "Forgiveness means emotional release; remission means forgetting",
     "Forgiveness is from God; remission is from people",
     "Forgiveness acknowledges the wrong; remission erases the consequence",
     "Forgiveness covers sin; remission takes sin away completely"),
    (7, "Why does God allow choice even though He has foreknowledge?",
     "Because without free will, judgment would be unjust",
     "Because some people force God’s hand through prayer",
     "Because predestination cancels out His sovereignty",
     "Because choice makes salvation feel more meaningful"),
    (8, "How is “re-creation” in Christ significant to the believer?",
     "It shows that God works in cycles of nature",
     "It symbolizes moral improvement through effort",
     "It refers to changing religions or denominations",
     "It marks the believer’s entry into a new spiritual identity"),
    (9, "Which of the following is the most accurate description of spiritual death?",
     "The punishment of sin in the grave",
     "The process of losing spiritual awareness",
     "A state of separation from God due to sin",
     "The curse that brings illness and death"),
    (10, "Which statement about predestination aligns most closely with your notes?",
     "God forces people to choose salvation because He knows their future",
     "Predestination means God planned people’s salvation journey beforehand",
     "It means some people are born saved, others are not",
     "It replaces the need for evangelism"),
    (11, "What does it mean when we say Jesus is the propitiation for our sins?",
     "He gave us a new religion",
     "He acted as a bridge for prayers",
     "He satisfied the demands of God’s justice on our behalf",
     "He helped us hide from God’s wrath"),
    (12, "Why does God punish sin, even when committed by those He loves?",
     "Because His justice is impartial and unchanging",
     "Because He is easily offended",
     "Because love must include discipline",
     "Because sin weakens His power"),
    (13, "How is reconciliation different from forgiveness alone?",
     "Reconciliation only involves emotions",
     "Reconciliation focuses on punishment",
     "Reconciliation restores a relationship that was broken",
     "Reconciliation means forgetting everything"),
    (14, "Why is understanding salvation necessary for spiritual growth?",
     "So we can help others become Christians",
     "So our salvation cannot be taken away from us",
     "So we can perform more miracles",
     "So our church attendance increases"),
    (15, "What does “Soteria,” the Greek word for salvation, emphasize?",
     "Gaining wealth through spiritual blessings",
     "Deliverance from harm, loss, and destruction",
     "Escaping physical trials",
     "Obtaining positions in church"),
    (16, "How does Adam being a “corporate man” affect our understanding of sin?",
     "It means everyone is innocent until they sin",
     "It means all were born after the resurrection",
     "It means when Adam sinned, we all sinned in him",
     "It means Adam was the first to be born again"),
    (17, "What is the role of the human will in receiving salvation?",
     "None, since God chooses for us",
     "To resist the devil and do good works",
     "To choose to believe and confess Christ",
     "To negotiate with God through prayer"),
    (18, "Why is salvation considered free but not cheap?",
     "Because it was paid for by someone else’s life",
     "Because it leads to expensive responsibilities",
     "Because it’s only available to serious people",
     "Because it is rare and costly"),
    (19, "What is the danger of not understanding key salvation terms like regeneration and righteousness?",
     "You may get the terms wrong in exams",
     "You may lose confidence in prayer",
     "Your salvation may be doubted or confused by others",
     "You may fail to join a church"),
    (20, "How does the devil exploit believers who are ignorant of their righteousness?",
     "By making them forget God",
     "By accusing them and keeping them bound in guilt",
     "By turning them against the church",
     "By encouraging them to evangelize"),
    (21, "What happens when a believer lacks assurance of forgiveness?",
     "They pray longer than necessary",
     "They live as though God is angry",
     "They stop tithing",
     "They attend multiple churches"),
    (22, "What was Satan’s attempt to overthrow God really about, according to the notes?",
     "He wanted to deceive angels",
     "He challenged the fairness of God’s justice",
     "He sought worship from humans",
     "He wanted to be more powerful than Jesus"),
    (23, "Which of these best reflects a misunderstanding of grace?",
     "Thinking you don’t deserve it",
     "Thinking grace means sin doesn’t matter",
     "Accepting grace through faith",
     "Believing grace came through Christ"),
    (24, "Why must a person be born before they can be called a sinner?",
     "Because sin is spiritual and hereditary",
     "Because babies inherit sin through baptism",
     "Because until one exists, they are not in Adam",
     "Because sin only applies after adulthood"),
    (25, "How does understanding predestination affect how a believer handles temptation?",
     "It makes temptation unnecessary",
     "It makes them careless since they are chosen",
     "It helps them resist by focusing on God’s plan for their destiny",
     "It removes responsibility for their actions"),
    (26, "How does the new creation differ from the old man?",
     "The old man is wiser",
     "The new creation has a new spirit but the same body",
     "The new creation loses memories of sin",
     "The old man had more access to grace"),
    (27, "Why is it important to believe in the heart before confessing with the mouth?",
     "Because speaking first shows pride",
     "Because faith must be rooted in conviction, not performance",
     "Because confession without belief is still effective",
     "Because the heart is the source of miracles"),
    (28, "Which of the following best illustrates the inflexibility of God’s justice?",
     "His unwillingness to forgive repeated sin",
     "His demand for perfect obedience",
     "His punishment of Satan, Adam, and even His own Son for sin",
     "His refusal to explain Himself to humanity"),
    (29, "What does Romans 6:6 suggest about our relationship with sin after salvation?",
     "Sin no longer exists",
     "We are free to choose sin without consequences",
     "Sin no longer has dominion over us",
     "We must fight to earn freedom from sin"),
    (30, "Why is it dangerous to base salvation on emotions or personal feelings?",
     "Because emotions are often misinterpreted as the voice of God",
     "Because faith is about thinking, not feeling",
     "Because feelings are needed only during worship",
     "Because emotion is required to receive miracles")
]

SECTION_B = [
    (1, "Ben is a university student who recently gave his life to Christ after years of atheism. He is passionate about attending church and has even joined the evangelism team. However, after falling into a repeated sinful habit, he becomes overwhelmed with guilt. He starts to feel unworthy, loses boldness in prayer, avoids fellowship, and begins to believe God has withdrawn His forgiveness.\n\nOne day in church, he hears a teaching on “righteousness by faith” and how “Jesus overpaid for our sins.” He is confused because it sounds like people are being encouraged to take sin lightly. He tells a friend, “I know Jesus died for me, but I still feel like I must do good to earn God’s love again. And I must constantly ask for forgiveness.”\n\nHis friend showed him what Christ accomplished in us through redemption and explains that his forgiveness is based on justice, not God’s mood. But Ben still struggles to believe he’s accepted. He stops serving in church because he thinks he has lost his inheritance in Christ.\n\nAs a shepherd to Ben and someone grounded in the teaching on the vocabularies of salvation, write an essay to explain to Ben:\n\ta. The true meaning of righteousness and why it is not based on conduct\n\tb. the misconceptions he has about forgiveness  and how he breaks the principle of jeopardy\n\tc. What Christ accomplished through redemption using the various levels of redemption\n\td. How knowledge of these truths affects fruitfulness and Christian identity\n\nYour essay must be scripture-based and directly reflect the content of the teachings of salvation grace and sin. (15 marks)"),
    (2, "Many Christians sincerely accept Christ as their Lord and Savior, yet they continue to struggle with sinful habits and carry a deep sense of unworthiness or spiritual defeat. This often leads them to question their salvation or feel disqualified in their walk with God. Based on the teaching on regeneration explain why this inner conflict may persist even after salvation. Additionally, discuss how a proper understanding of the importance of regeneration can help them overcome it. (5 marks)"),
    (3, "It is common for believers especially those who make mistakes or fall into sin  to feel as though God is angry with them or disappointed in their actions. This fear can create distance in their relationship with God and lead to guilt-driven Christianity. Using your understanding of propitiation explain how Jesus Christ, through His sacrifice, removed God’s anger once and for all and explain how understanding propitiation helps a believer walk in boldness, rather than fear, before God. (5 marks)"),
    (4, "One of the major challenges in the lives of many believers is a constant sense of guilt and spiritual stagnation due to their past sins. Even though they are saved, they continue to live under condemnation because they do not fully understand the depth of God’s forgiveness. According to the teaching on remission explain what happens when a believer lacks this understanding and how a proper understanding of remission can free believers from cycles of guilt and empower them to serve God more passionately. (5MARKS)"),
    (5, "The word “Salvation” comes from the Greek word Soteria, which means preservation or deliverance from harm, loss, or destruction. According to the teachings, one of the greatest dangers of sin is that its wages are spiritual and physical death. God’s nature, built on justice and righteousness, demands that sin be punished. From this perspective, using the concept of spiritual death, and the inflexibility of God’s justice explain why salvation is absolutely necessary for every human being. (5MARKS)"),
    (6, "A student says, “I’m too busy with school to serve God.” Use the doctrine of redemption to challenge this mindset and explain why a believer must never trivialize the cost of their salvation. (5 MARKS)."),
    (7, "One major distinction between Old Testament forgiveness and New Testament forgiveness lies in the concepts of atonement and remission. Discuss in detail the difference between atonement and remission and analyze how the teaching of remission affects a believer’s view of past, present, and future sins. (5Marks)")
]
